all: Ricker_rb_ratiovar.dll

Ricker_rb_ratiovar.dll: Ricker_rb_ratiovar.cpp
	Rscript --vanilla -e "TMB::compile('Ricker_rb_ratiovar.cpp')"

Rickerkf.dll: Rickerkf.cpp
	Rscript --vanilla -e "TMB::compile('Rickerkf.cpp')"

clean:
	rm -rf *o
