all: banana avocado

banana: Ricker_rb_ratiovar.cpp
	Rscript --vanilla -e "TMB::compile('Ricker_rb_ratiovar.cpp')"

avocado: Rickerkf.cpp
	Rscript --vanilla -e "TMB::compile('Rickerkf.cpp')"

clean:
	rm -rf *o
